server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  application:
    name: order-service

  sql:
    init:
      mode: always
      platform: postgresql
      schema-locations: classpath:schema.sql

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ordersdb
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

app:
  rabbitmq:
    exchange: store.events

    payment-processed-queue: payment.processed.queue.order
    payment-failed-queue: payment.failed.queue.order
    stock-reserved-queue: stock.reserved.queue.order
    stock-reservation-failed-queue: stock.failed.queue.order
    cart-converted-queue: cart.converted.queue.order
    payment-queue: payment.command.queue.order

    payment-processed-key: payment.processed
    payment-failed-key: payment.failed
    stock-reserved-key: stock.reserved
    stock-reservation-failed-key: stock.failed
    cart-converted-key: cart.converted.event
    process-payment-key: payment.process
    order-shipped-key: order.shipped
    order-delivered-key: order.delivered
  
  reports:
    sales-dir: D:\Enyoi - Acelera TI\enyoi-store\reports\sales_reports
  notifications:
    base-url: http://localhost:8088
    test-recipient: rikbarahona@gmail.com

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
